---
- name: setup group
  group:
   name: "{{ freezer_group }}"
   system: yes

- name: Setup user
  user:
   name: "{{ freezer_user }}"
   system: yes
   group: "{{ freezer_group }}"

- name: Create /etc/freezer directory
  file:
    state: directory
    owner: "{{ freezer_user }}"
    path:  "{{ item }}"
  with_items:
    - "{{ freezer_home }}"
    - "{{ freezer_agent_install_dir }}"

- name: Install freezer-agent dependiences
  package:
    name: '{{ item }}'
    state: present
    update_cache: yes
    force: yes
  with_items:
    - python-pip
    - python-virtualenv
    - libssl-dev
    - libffi-dev
    - python-dev
    - git

- name: Install freezer-agent
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version | default(omit)}}"
    editable: false
    virtualenv_command: virtualenv
    virtualenv: "{{ freezer_agent_install_dir }}"
  with_items:
    ## XXX: we should change requirements.txt to force python-novaclient==7.1.0
    - name: "git+https://github.com/openstack/freezer.git@{{ freezer_revision }}"
    - name: python-novaclient

- name: Configure systemd services
  include_role:
    name: systemd-service
  vars:
    systemd_service: "{{ freezer_agent_services }}"