---

- name: Check if variables are defined as needed
  assert:
    that:
      - freezer_openstack_auth_url is defined
      - freezer_openstack_password is defined

- include: install.yml

- include: start.yml